### ISSUE TITLE
What do your event streams look like?

### ISSUE THREAD

**Issue by bennage** [MicrosoftArchive/iot-journey#167]
We are interested to know what _your_ event streams look like. 
- Are you sending different types of events? That is, are there different schemas? or do all the events fit into a common schema?
- What is the event velocity? That is, how many events per second does a device send? How many events per second does the backend handle overall?
- Is our event traffic bursty or continuous?
- What are you using for protocol and encoding?
- Anything else that is interesting about your events?

**Comment by maxal1917** [comment]
Our company provides GPS tracking solution for businesses. Thus, GPS positions and some additional events can come from two different sources.
1. Smartphones. In this case smartphones represent "field gateway" and we are flexible in defining the format and schema of such events. In our new application we have RESTful Web Api hosted in Azure as Web role, with JSON serialization. Usual Authorize header is used for authorization, with Bearer authorization schema.
2. Hardmount devices. In this case data are sent over UDP. We have little bit of control over format of the message, but this is something we prefer not to modify wherever possible. So, currently it's some binary format over UDP. For new solution (to be implemented yet) we plan to provide endpoints in worker role.

Velocity: If device is moving, typically events come once per minute, otherwise once per hour. This is for GPS positions. On top of that there are additional "events", like ignition on/off, acceleration and other data from sensors. Typically few per hour.

Pattern: Continues pattern with one caveat. Devices (both hardmounts and phones) can go out of cell phone coverage, in which case data are cached on the device, and then sent in batches.

Protocols: HTTPS + JSON + Authentication with HTTP headers for some metadata (device Serial Number). This was our choice. UDP for hardmounts, custom formatting, binary, not our choice.

For out processing it is important to process events in correct order. For example, if we have Ignition On and Ignition Off, we need to process them in this order. And it's important to process last few positions for the processing. Example: to detect some alerts, we use average values from last (n) events, otherwise we can have too many false alerts. Some events are actually need to be converted based on custom setup.
Example: some device can have 5 sensors. Some customers install those devices on bus, where data from sensor 1 represent opening bus doors. Same device can be installed by other customer on snow removal machine, where sensor 1 would be some other device on this machine. Events will have just "data from sensor 1", to have any meaningful interpretation, we need to convert it based on some configuration.

If I think of something else, I will add later. Thanks.

**Comment by tomkerkhove** [comment]
Here is some information about our event data -
* We have three types of events (temperature, electricity & solar logs) that have their own JSON schema although a part of it is shared
* All data is batched and sent in specific intervals - Electricity every 15 minutes while temperature & solar logs are sent every 5 minutes.
* Traffic is continuous *(but batched as just mentioned)*
* Devices send to the field gateway by using Zigbee
* Field gateway sends to Azure with AMQP
* Everything is JSON encoded

**Comment by fteigen** [comment]
* Currently all events use the same schema
* Generally event traffic is continuous at one minute intervals.
* Events are JSON encoded
* Events are sent by HTTPS to the Event hub through the REST API.

**Comment by bennage** [comment]
Thanks to everyone! This is very useful.
