### ISSUE TITLE
Journal Entry: Device Registry & Provisioning

### ISSUE THREAD

**Issue by bennage** [MicrosoftArchive/iot-journey#194]
See #184 for context.
- [ ] common requirements
- [x] Fabrikam's requirements
- [ ] logical solutions
- [ ] technology options
- [ ] security concerns
- [ ] learnings

**Comment by bennage** [comment]
### Fabrikam's requirements

In order for Fabrikam to provide its services to building managers, devices must first be installed in the buildings. These devices will not be able to communicae with Fabrikam's backend until they have been _provisioned_. By _provision_ we specifically mean _authorizing a specific device to transmit events to the backend service_.
- A technician will physically install the device in a building. 
- Each device will already have an identifier (a GUID that uniquely identifies the device)
- A security token, specific to the device will be generated and assigned to the device at the time of installation. The token is assocated to the device identifier.
- The technician will use a mobile app to complete the provision.The mobile app will use a provision API. 
    - The API will require authentication of the technician.
   - The API  will require the device identifier as input.
   - The API will return the token.

In addition to the provisioning process, there is additional information that is recorded at the time that a device is installed. This information is metadata associated with the device identifier in a cloud-hosted _device registry_.
- location where the device is installed (building, room, location in room)
- identity of the technician performing the installation
- date and time when the installation occurred

**Comment by fteigen** [comment]
Would it make sense to differentiate between device and gateway? I think it was mentioned in another Journal entry that a gateway is a type of device, but I assume that security tokens apply to gateways only, as the communication between devices and the cloud go through the gateway. Obviously, in some cases device and gateway will be one and the same, but in other cases there may be multiple devices communicating through the same gateway and in this case would they not share the same security token?

**Comment by bennage** [comment]
@fteigen In some contexts they do need to be differentiated, but not  in others. 
I haven't yet seen a senario where multiple devices communicate _through_ a field gateway and retain independent credentials. I'd be interested in details if you have a scenario like this.

Our current understanding for this kind of situation is that the gateway and associated devices would exist inside a common trust boundary and that the gateway would be the trusted agent for communicating outside the boundary (to the cloud-hosted backend). The field gateway would need to trust the devices, and some identifier would be passed along when transmitting their events, but backend would only need to authenticate the gateway.

Please let us know if you see a different scenario.

**Comment by fteigen** [comment]
@bennage I think we are in agreement, because what you're writing in your second paragraph ("Our current understanding ...") was precisely the point I was trying to make. 

In your journal entry, however, you write "A security token, specific to the device will be generated ...". I may have misunderstood this, but I assume you only need a security token per gateway, or do you equate device and gateway in this context? 

I see that you write in the introduction to the entry that "By provision we specifically mean authorizing a specific device to transmit events to the backend service", and if we agree that you only need to authorize the gateway wouldn't this definition be too constrictive?

I'll try to explain what I mean by an example from the Fabrikam scenario. Let's say that there is one gateway per apartment, and you're installing a new gateway in an apartment and a smoke detector is attached to the gateway. In the provisioning process you'll need to get an id and a security token for the gateway, right? But wouldn't you also need to get an id for the smoke detector? 

Also, while I assume that while capturing metadata in the device registry (e.g. location where the device is installed (building, room, location in room)) it will be more important to capture the location of the smoke detector than the location of the gateway, although this would also be useful.

Finally, when you a month later install a second smoke detector, which talks to the same gateway, in the apartment, you would not need a new security token, but I assume you would still want to include this device and the location of the device in the device registry?!
